In [1]:
#Importando librer√≠a de pandas

import pandas as pd

In [10]:
#Cargando los datos

arc = pd.read_csv('data.csv')

#Si se tiene alg√∫n tipo de identificador dentro de los datos para las columnas

#arc = pd.read_csv('data.csv', index_col = 'id')

arc

#Visualizandolos

#arc           #Muestra todos los datos

#arc.head()    #Muestra los primeros
#arc.tail()    #Muestra los √∫ltimos
#arc.head(3)    #Muestra los n primeros datos
#arc.tail(3)    #Muestra los n √∫ltimos datos

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44‚Ä¶,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! üôå,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ‚úàÔ∏è,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [9]:
#Estad√≠stica

arc.describe()

        favorites    retweets   mentions   followers    followees
count   26.000000   26.000000  26.000000   26.000000    27.000000
mean   280.538462   80.000000  15.423077  352.807692  1190.185185
std    153.377242   40.303846   9.596554  375.319493  1965.735995
min     23.000000   21.000000   1.000000   12.000000   129.000000
25%    139.250000   45.500000   8.250000   21.000000   258.000000
50%    305.500000   79.000000  16.000000  332.000000   351.000000
75%    422.500000  110.750000  23.500000  389.000000  1822.000000
max    500.000000  146.000000  29.000000  982.000000  9918.000000

In [1]:
print('Hola Julio')

Hola Julio